version: '3.0'

x-common-env: &common-env
  QUESTION_ENDPOINT: http://questionservice:1234
  ANSWER_ENDPOINT: http://answerservice:5678

services:

  gatewayservice:
    build: ./gatewayservice
    image: deep-thought/gatewayservice
    container_name: gatewayservice
    environment:
      <<: *common-env
    networks:
      deep-thought:
    ports:
      - "4242:4242"

  questionservice:
    build: ./questionservice
    image: deep-thought/questionservice
    container_name: questionservice
    environment:
      <<: *common-env
    networks:
      deep-thought:
    ports:
      - "1234:1234"

  answerservice:
    build: ./answerservice
    image: deep-thought/answerservice
    container_name: answerservice
    environment:
      <<: *common-env
    networks:
      deep-thought:
    ports:
      - "5678:5678"

networks:
  deep-thought: