receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp/hny:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": $HONEYCOMB_API_KEY

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/hny]